TILE_MAP = (17, 62)
TILE = (25, 7)
TILE_PADDING = 3



_levels = {
    0: {
        'bricks': ['                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '     r     r     ',
                   '     rr   rr     ',
                   '    rrr   rrr    ',
                   '    rrr   rrr    ',
                   '    rrr   rrr    ',
                   '    rrrr rrrr    ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrr   rrrrr  ',
                   '  rrrrr   rrrrr  ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrrr rrrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   '  rr         rr  ',
                   '  r           r  ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 '],
        'name': 'The Lungs',
        'powerups': {
            1: {'pu_type': 'longer'},
            3: {'pu_type': 'pack', 'amount': 1},
            5: {'pu_type': 'shoot', 'timer': 6000},
            20: {'pu_type': 'shorter'},
            27: {'pu_type': 'metastasis', 'amount': 3},
            33: {'pu_type': 'longer'},
            40: {'pu_type': 'shoot', 'timer': 6000},
            50: {'pu_type': 'hotball', 'timer': 2000},
            51: {'pu_type': 'hotball', 'timer': 2000},
            60: {'pu_type': 'hotball', 'timer': 2000},
            65: {'pu_type': 'longer'},
            70: {'pu_type': 'metastasis', 'amount': 3},
            80: {'pu_type': 'shoot', 'timer': 3000},
            87: {'pu_type': 'shoot', 'timer': 1000},
            89: {'pu_type': 'shoot', 'timer': 1000},
            92: {'pu_type': 'shoot', 'timer': 1000},
            96: {'pu_type': 'metastasis', 'amount': 3},
            100: {'pu_type': 'metastasis', 'amount': 2},
            104: {'pu_type': 'shoot', 'timer': 3000},
            106: {'pu_type': 'shoot', 'timer': 1000},
            108: {'pu_type': 'shoot', 'timer': 1000},
            110: {'pu_type': 'hotball', 'timer': 3000},
            115: {'pu_type': 'longer'},
            119: {'pu_type': 'hotball', 'timer': 3000},
            122: {'pu_type': 'hotball', 'timer': 2000},
            130: {'pu_type': 'metastasis', 'amount': 3},
            140: {'pu_type': 'shoot', 'timer': 3000},
            150: {'pu_type': 'metastasis', 'amount': 1},
            160: {'pu_type': 'metastasis', 'amount': 3},
            170: {'pu_type': 'shoot', 'timer': 3000},
            180: {'pu_type': 'metastasis', 'amount': 3},
            190: {'pu_type': 'metastasis', 'amount': 1},
            200: {'pu_type': 'shorter'},
            210: {'pu_type': 'shoot', 'timer': 3000},
            220: {'pu_type': 'longer'},
            230: {'pu_type': 'shoot', 'timer': 3000},
            235: {'pu_type': 'longer'},
            240: {'pu_type': 'shoot', 'timer': 3000},
            250: {'pu_type': 'hotball', 'timer': 3000},
            253: {'pu_type': 'hotball', 'timer': 2000},
            255: {'pu_type': 'shoot', 'timer': 3000},
            # 260: {'pu_type': 'metastasis', 'amount': 1},
            261: {'pu_type': 'metastasis', 'amount': 2},
            263: {'pu_type': 'shorter'},
            268: {'pu_type': 'longer'},
            270: {'pu_type': 'hotball', 'timer': 4000},
            280: {'pu_type': 'shoot', 'timer': 3000},
            290: {'pu_type': 'metastasis', 'amount': 2},
            300: {'pu_type': 'shoot', 'timer': 3000},
            310: {'pu_type': 'metastasis', 'amount': 2},
            320: {'pu_type': 'shoot', 'timer': 3000},
            330: {'pu_type': 'metastasis', 'amount': 2},
            340: {'pu_type': 'shoot', 'timer': 3000},
            # 350: {'pu_type': 'metastasis', 'amount': 2},
            360: {'pu_type': 'shoot', 'timer': 3000},
            370: {'pu_type': 'metastasis', 'amount': 2},
            373: {'pu_type': 'shoot', 'timer': 3000},

        },
        'bonus_time': 300
    },
    1: {
        'bricks': ['                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '      w   w     ',
                   '     www www    ',
                   '    wwwwwwwww   ',
                   '    wwwwwwwww   ',
                   '    wwwwwwwww   ',
                   '    wwwwwwwww   ',
                   '     wwwwwww    ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '      wwwww     ',
                   '     wwwwwww    ',
                   '    wwwwwwwww   ',
                   '    wwwwwwwww   ',
                   '    wwwwwwwww   ',
                   '    wwwwwwwww   ',
                   '     www www    ',
                   '      w   w     ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                ',
                   '                '],
        'name': 'The Bone',
        'powerups': {
            2: {'pu_type': 'longer'},
            5: {'pu_type': 'shoot', 'timer': 6000},
            14: {'pu_type': 'metastasis', 'amount': 3},
            20: {'pu_type': 'shorter'},
            27: {'pu_type': 'metastasis', 'amount': 3},
            33: {'pu_type': 'longer'},
            40: {'pu_type': 'shoot', 'timer': 6000},
            50: {'pu_type': 'hotball', 'timer': 3000},
            55: {'pu_type': 'hotball', 'timer': 2000},
            65: {'pu_type': 'longer'},
            70: {'pu_type': 'metastasis', 'amount': 3},
            80: {'pu_type': 'shoot', 'timer': 3000},
            87: {'pu_type': 'shoot', 'timer': 1000},
            89: {'pu_type': 'shoot', 'timer': 1000},
            92: {'pu_type': 'shoot', 'timer': 1000},
            96: {'pu_type': 'metastasis', 'amount': 3},
            100: {'pu_type': 'metastasis', 'amount': 2},
            104: {'pu_type': 'shoot', 'timer': 3000},
            106: {'pu_type': 'shoot', 'timer': 1000},
            108: {'pu_type': 'shoot', 'timer': 1000},
            110: {'pu_type': 'hotball', 'timer': 3000},
            115: {'pu_type': 'longer'},
            119: {'pu_type': 'hotball', 'timer': 2000},
            120: {'pu_type': 'hotball', 'timer': 2000},
            122: {'pu_type': 'hotball', 'timer': 2000},
            130: {'pu_type': 'metastasis', 'amount': 3},
            140: {'pu_type': 'shoot', 'timer': 3000},
            150: {'pu_type': 'metastasis', 'amount': 1},
            160: {'pu_type': 'metastasis', 'amount': 3},
            170: {'pu_type': 'shoot', 'timer': 3000},
            180: {'pu_type': 'metastasis', 'amount': 3},
            190: {'pu_type': 'metastasis', 'amount': 1},
            200: {'pu_type': 'shorter'},
            210: {'pu_type': 'shoot', 'timer': 3000},
            216: {'pu_type': 'pack', 'amount': 1},
        },
        'bonus_time': 300
    },
    2: {
        'bricks': ['                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '      r   r      ',
                   '   rr rr rr rr   ',
                   '  rrrrrr rrrrrr  ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rr  rrrrrrr  rr ',
                   ' r   rrrrrrr   r ',
                   ' r   rrrrrrr   r ',
                   ' rr  rrrrrrr  rr ',
                   ' rr  rrrrrrr  rr ',
                   '  rr rrrrrrr rr  ',
                   '  rr rrrrrrr rr  ',
                   '   r  rrrrr  r   ',
                   '      rrrrr      ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '       rrr       ',
                   '        r        ',
                   '        r        ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 '],
        'name': 'The Ovary',
        'powerups': {
            2: {'pu_type': 'shoot', 'timer': 4000},
            5: {'pu_type': 'longer'},
            14: {'pu_type': 'metastasis', 'amount': 2},
            20: {'pu_type': 'shorter'},
            27: {'pu_type': 'metastasis', 'amount': 2},
            33: {'pu_type': 'longer'},
            40: {'pu_type': 'shoot', 'timer': 6000},
            50: {'pu_type': 'hotball', 'timer': 3000},
            55: {'pu_type': 'hotball', 'timer': 2000},
            65: {'pu_type': 'longer'},
            70: {'pu_type': 'metastasis', 'amount': 2},
            80: {'pu_type': 'shoot', 'timer': 3000},
            # 87: {'pu_type': 'shoot', 'timer': 1000},
            # 89: {'pu_type': 'shoot', 'timer': 1000},
            92: {'pu_type': 'shoot', 'timer': 3000},
            96: {'pu_type': 'metastasis', 'amount': 1},
            100: {'pu_type': 'metastasis', 'amount': 2},
            104: {'pu_type': 'shoot', 'timer': 3000},
            166: {'pu_type': 'pack', 'amount': 1},
            # 108: {'pu_type': 'shoot', 'timer': 1000},
            110: {'pu_type': 'hotball', 'timer': 3000},
            115: {'pu_type': 'longer'},
            # 119: {'pu_type': 'hotball', 'timer': 2000},
            120: {'pu_type': 'hotball', 'timer': 3000},
            # 122: {'pu_type': 'hotball', 'timer': 2000},
            130: {'pu_type': 'metastasis', 'amount': 1},
            140: {'pu_type': 'shoot', 'timer': 3000},
            150: {'pu_type': 'metastasis', 'amount': 1},
            160: {'pu_type': 'metastasis', 'amount': 3},
        },
        'bonus_time': 300
    },
    3: {
        'bricks': ['                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '      rrrrrrr    ',
                   '     rrrrrrrrr   ',
                   '    rrrrrrrrrrr  ',
                   '    rrrrrrrrrrr  ',
                   '    rrr     rrr  ',
                   '   rrr       rrr ',
                   '   rrr       rrr ',
                   '   rr         rr ',
                   '   rr         rr ',
                   '   rr         rr ',
                   '   rr         rr ',
                   '   rr         rr ',
                   '   rrr       rrr ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '    rr       rr  ',
                   '   rrr       rrr ',
                   '   rr         rr ',
                   '   rr         rr ',
                   '   rr         rr ',
                   '   rr         rr ',
                   '   rr         rr ',
                   '   rr        rrr ',
                   '    rr      rrr  ',
                   '    rr   rrrrrr  ',
                   '    rr   rrrrrr  ',
                   '     r   rrrrr   ',
                   '         rrrr    ',
                   '         rr      ',
                   '         rr      ',
                   '         r       ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 '],
        'name': 'The Large Bowel',
        'powerups': {
            2: {'pu_type': 'shoot', 'timer': 4000},
            5: {'pu_type': 'longer'},
            14: {'pu_type': 'metastasis', 'amount': 2},
            20: {'pu_type': 'shorter'},
            27: {'pu_type': 'metastasis', 'amount': 2},
            33: {'pu_type': 'longer'},
            40: {'pu_type': 'shoot', 'timer': 6000},
            50: {'pu_type': 'hotball', 'timer': 4000},
            65: {'pu_type': 'longer'},
            70: {'pu_type': 'metastasis', 'amount': 2},
            80: {'pu_type': 'shoot', 'timer': 3000},
            92: {'pu_type': 'shoot', 'timer': 1000},
            96: {'pu_type': 'metastasis', 'amount': 2},
            100: {'pu_type': 'metastasis', 'amount': 2},
            104: {'pu_type': 'shoot', 'timer': 3000},
            110: {'pu_type': 'hotball', 'timer': 3000},
            115: {'pu_type': 'longer'},
            120: {'pu_type': 'hotball', 'timer': 3000},
            130: {'pu_type': 'metastasis', 'amount': 1},
            140: {'pu_type': 'shoot', 'timer': 3000},
            150: {'pu_type': 'metastasis', 'amount': 2},
            180: {'pu_type': 'pack', 'amount': 1},
            190: {'pu_type': 'metastasis', 'amount': 3},
        },
        'bonus_time': 300
    },
    4: {
        'bricks': ['                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '    rrr   rrr    ',
                   '   rrrr   rrrr   ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrr   rrrrr  ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   ' rrrrrr   rrrrrr ',
                   '  rrrrr   rrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '   rrrrr rrrrr   ',
                   '   rrrr   rrrr   ',
                   '    rrr   rrr    ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 '],
        'name': 'The Kidneys',
        'powerups': {
            1: {'pu_type': 'longer'},
            3: {'pu_type': 'pack', 'amount': 1},
            5: {'pu_type': 'shoot', 'timer': 5000},
            20: {'pu_type': 'shorter'},
            27: {'pu_type': 'metastasis', 'amount': 2},
            33: {'pu_type': 'longer'},
            40: {'pu_type': 'shoot', 'timer': 5000},
            50: {'pu_type': 'hotball', 'timer': 2000},
            51: {'pu_type': 'hotball', 'timer': 2000},
            60: {'pu_type': 'hotball', 'timer': 2000},
            65: {'pu_type': 'longer'},
            70: {'pu_type': 'metastasis', 'amount': 1},
            80: {'pu_type': 'shoot', 'timer': 3000},
            90: {'pu_type': 'metastasis', 'amount': 1},
            100: {'pu_type': 'shoot', 'timer': 3000},
            108: {'pu_type': 'shoot', 'timer': 1000},
            110: {'pu_type': 'hotball', 'timer': 3000},
            120: {'pu_type': 'hotball', 'timer': 4000},
            130: {'pu_type': 'metastasis', 'amount': 1},
            140: {'pu_type': 'shoot', 'timer': 3000},
            150: {'pu_type': 'metastasis', 'amount': 1},
            160: {'pu_type': 'metastasis', 'amount': 1},
            170: {'pu_type': 'shoot', 'timer': 3000},
            180: {'pu_type': 'metastasis', 'amount': 1},
            190: {'pu_type': 'shorter'},
            200: {'pu_type': 'metastasis', 'amount': 1},
            210: {'pu_type': 'shoot', 'timer': 3000},
            220: {'pu_type': 'longer'},
            230: {'pu_type': 'shoot', 'timer': 3000},
            240: {'pu_type': 'shoot', 'timer': 3000},
            250: {'pu_type': 'hotball', 'timer': 3000},
            260: {'pu_type': 'metastasis', 'amount': 1},
            263: {'pu_type': 'shorter'},
            268: {'pu_type': 'longer'},
            270: {'pu_type': 'hotball', 'timer': 4000},
            280: {'pu_type': 'shoot', 'timer': 3000},
            290: {'pu_type': 'metastasis', 'amount': 1},
            300: {'pu_type': 'shoot', 'timer': 3000},
            310: {'pu_type': 'metastasis', 'amount': 1},
            320: {'pu_type': 'shoot', 'timer': 3000},
            330: {'pu_type': 'metastasis', 'amount': 2},
            340: {'pu_type': 'shoot', 'timer': 3000},
        },
        'bonus_time': 300
    },
    5: {
        'bricks': ['                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '     r     r     ',
                   '   rrrr   rrrr   ',
                   '   rrrr   rrrr   ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrr rrrrrr  ',
                   '  rrrrrrrrrrrrr  ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   ' rrrrrrrrrrrrrrr ',
                   '  rrrrrrrrrrrrr  ',
                   '  rrrrrrrrrrrrr  ',
                   '  rrrrrrrrrrrrr  ',
                   '   rrrrrrrrrrr   ',
                   '   rrrrrrrrrrr   ',
                   '    rrrrrrrrr    ',
                   '    rrrrrrrrr    ',
                   '     rrrrrrr     ',
                   '     rrrrrrr     ',
                   '      rrrrr      ',
                   '      rrrrr      ',
                   '       rrr       ',
                   '       rrr       ',
                   '        r        ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 ',
                   '                 '],
        'name': 'The Heart',
        'powerups': {
            1: {'pu_type': 'longer'},
            3: {'pu_type': 'shorter'},
            5: {'pu_type': 'shoot', 'timer': 2000},
            20: {'pu_type': 'shorter'},
            27: {'pu_type': 'metastasis', 'amount': 3},
            33: {'pu_type': 'longer'},
            40: {'pu_type': 'shoot', 'timer': 6000},
            50: {'pu_type': 'hotball', 'timer': 2000},
            # 51: {'pu_type': 'hotball', 'timer': 2000},
            60: {'pu_type': 'hotball', 'timer': 2000},
            # 65: {'pu_type': 'longer'},
            70: {'pu_type': 'metastasis', 'amount': 1},
            80: {'pu_type': 'shoot', 'timer': 3000},
            # 87: {'pu_type': 'shoot', 'timer': 1000},
            # 89: {'pu_type': 'shoot', 'timer': 1000},
            92: {'pu_type': 'shoot', 'timer': 3000},
            # 96: {'pu_type': 'metastasis', 'amount': 3},
            100: {'pu_type': 'metastasis', 'amount': 1},
            # 104: {'pu_type': 'shoot', 'timer': 3000},
            # 106: {'pu_type': 'shoot', 'timer': 1000},
            # 108: {'pu_type': 'shoot', 'timer': 1000},
            110: {'pu_type': 'hotball', 'timer': 3000},
            115: {'pu_type': 'longer'},
            # 119: {'pu_type': 'hotball', 'timer': 2000},
            # 120: {'pu_type': 'hotball', 'timer': 3000},
            # 122: {'pu_type': 'hotball', 'timer': 2000},
            130: {'pu_type': 'metastasis', 'amount': 1},
            140: {'pu_type': 'shoot', 'timer': 3000},
            150: {'pu_type': 'metastasis', 'amount': 1},
            160: {'pu_type': 'metastasis', 'amount': 1},
            # 170: {'pu_type': 'shoot', 'timer': 3000},
            180: {'pu_type': 'metastasis', 'amount': 1},
            190: {'pu_type': 'metastasis', 'amount': 1},
            200: {'pu_type': 'shorter'},
            210: {'pu_type': 'shoot', 'timer': 3000},
            220: {'pu_type': 'longer'},
            # 230: {'pu_type': 'shoot', 'timer': 3000},
            # 235: {'pu_type': 'longer'},
            240: {'pu_type': 'shoot', 'timer': 3000},
            250: {'pu_type': 'hotball', 'timer': 3000},
            # 253: {'pu_type': 'hotball', 'timer': 2000},
            # 255: {'pu_type': 'shoot', 'timer': 3000},
            260: {'pu_type': 'metastasis', 'amount': 1},
            # 261: {'pu_type': 'metastasis', 'amount': 2},
            263: {'pu_type': 'shorter'},
            # 268: {'pu_type': 'longer'},
            270: {'pu_type': 'hotball', 'timer': 4000},
            # 280: {'pu_type': 'shoot', 'timer': 3000},
            290: {'pu_type': 'metastasis', 'amount': 1},
            # 300: {'pu_type': 'shoot', 'timer': 3000},
            # 310: {'pu_type': 'metastasis', 'amount': 2},
            320: {'pu_type': 'shoot', 'timer': 3000},
            330: {'pu_type': 'metastasis', 'amount': 1},
            340: {'pu_type': 'shoot', 'timer': 3000},
            350: {'pu_type': 'hotball', 'timer': 4000},
            360: {'pu_type': 'metastasis', 'amount': 4},
            370: {'pu_type': 'metastasis', 'amount': 4},
            380: {'pu_type': 'metastasis', 'amount': 4}

        },
        'bonus_time': 300
    }
}
class Level:
    def __init__(self, no):
        global _levels
        self.no = no
        try:
            self.bricks = _levels.get(no).get('bricks')
        except AttributeError:
            print('Level {} not found.'.format(no))
        self.powerups = _levels.get(no).get('powerups')
        self.bonus_time = _levels.get(no).get('bonus_time')


def get_total_levels():
    return len(_levels)
